version: "3.9"

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/backend
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - pgdb
      - redis
  celery:
    build: ./backend
    container_name: celery
    command: celery -A core worker --loglevel=INFO
    volumes:
      - ./backend:/usr/src/app/backend
    env_file:
      - .env
    depends_on:
      - django
      - redis
  celery-beat:
    build: ./backend
    container_name: celery-beat
    command: celery -A core beat -l info
    volumes:
      - ./backend:/usr/src/app/backend
    depends_on:
      - redis
  pgdb:
    image: postgres
    container_name: pgdb
    env_file:
      - .env.db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pg_admin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/usr/src/app/backend/staticfiles
      - media_volume:/usr/src/app/backend/media
    depends_on:
      - django
  redis:
    image: "redis:alpine"
    container_name: redis
    expose:
      -  6379
    ports:
      - "6379:6379"
  flower:
    image: mher/flower
    container_name: flower
    command: [ "celery", "--broker=redis://redis:6379/0", "flower", "--port=8888" ]
    ports:
      - "8888:8888"
    depends_on:
      - redis
      - celery

volumes:
  pg_data:
  static_volume:
  media_volume:
  pg_admin: